### ISSUE TITLE
eCAL Mon: Add clean-output version that can be used in scripts

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#1008]
### Context

Currently, we have 3 eCAL Mon Versions:
1. The Qt GUI
2. The FTXUI (Console-based) TUI
3. The primitive CLI

### Proposal

Replace the primitive CLI with a more sophisticated version, as already explained in #494:

> A classic command line mode having MANY options. This mode should print a very clean STDOUT, either by default, or via an additonal parameter (--cleanoutput 🤔?), so this mode can also be used by other software and scripts to determine the state of anything in the eCAL network. In this mode, eCAL Mon CLI must always terminate in a forseeable (or configurable) time, so other scripts are not blocked.

### Tasks and updates

- [ ] Create a list of exact features, the CLI version should have
- [ ] Define the command line parameters. There will probably be a lot.
- [ ] Implement the Application 😀

**Comment by git-pi-e** [comment]
Is this planned for any future release?

**Comment by FlorianReimold** [comment]
@git-pi-e: No, this is not planned, yet.
