### ISSUE TITLE
Support MCAP as Measurement File format

### ISSUE THREAD

**Issue by KerstinKeller** [eclipse-ecal/ecal#1076]
### Context

Our current hdf5 measurement format has a few drawbacks:
- We don't support compression :(
- HDF5 can be hard to crosscompile
- New bug limit of message descriptor size (#1062)

The [MCAP format](https://foxglove.dev/mcap) is an alternative recording format, designed explicitly for the data recording usecase.

### Proposal

Let's support MCAP as a measurement output!

It can be configurable, which file format to write, with the default being HDF5. In the long run, this can be switched to MCAP and at some point (if all goes well) we might deprecate HDF5.

All reading applications (player / meas_cutter / C++ High-Level-API / Python API) should be able to read both formats.

### Tasks and updates

- [ ] Introduce a common base class with the old `eCALMeas` interface, so that the alternative implementation can serve as a drop-in
- [ ] create configuration item in eCAL.ini for eCAL Player / other apps (to decide which format to write)
- [ ] make an implementation for the base class based on mcap (what about options, etc (-> config items?) and itegrate dependencies via submodules
- [ ]  make a Reader factory function to create an appropriate Reader based on the actual measurement type.

**Comment by git-pi-e** [comment]
Will this be part of the 5.14 release?

**Comment by AntoineBassoul** [comment]
Any updates ? ROS still a gigantic over opinionated pain, but we need native recording visualization with foxglove xD
