### ISSUE TITLE
eCAL::core / eCAL::hdf5: per publisher datatype information

### ISSUE THREAD

**Issue by KerstinKeller** [eclipse-ecal/ecal#1237]
### Context

Internally, eCAL ist saving only one datatype information per unique "topic_name".
However we might have scenarios, where there are publishers and subscribers with differing Datatype information. Especially if there are two publishers in the system, which e.g publish on the same topic from different versions of a proto file.

Only chance  determines, which info will later be saved in the measurement or used for deserialization in eCAL Monitor.

This feature will require changes in many parts of eCAL, namely the core, hdf5, recorder and player.

### Proposal

We need to keep track of *all* available datatype information per topic_name, and connect them with publishers / subscribers respectively (given an ID?).
We then need to make this information available via API (maybe as member functions for pub / sub, or generally), and take them into account when creating measurements.

Maybe even a callback should have the information which publisher sent the topic.

Note: the publisher ID cannot just be an ID from the publisher process, as a process may have multiple publishers.

### Tasks and updates

- [ ] `eCAL::core`: make publisher ID available in callbacks
- [ ] `eCAL::core`: provide API for subscribers to get connected publishers  & their datatype information
- [ ] `eCAL::hdf5`: enhance API to save information with unique ID.
- [ ] `eCAL::hdf5`: enhance API to retrieve information with `EntryInfo`
- [ ] `Recorder`: connect publisher ID from callbacks with measurement
- [ ] `Player`: Possibly create multiple subscribers (e.g. one per original publisher)

This will be a rather large issue and might require multitple PRs to fix.
