### ISSUE TITLE
Naming inconsistency: Topic vs. Channel

### ISSUE THREAD

**Issue by TobiRamm** [eclipse-ecal/ecal#1317]
### Context

When I use the python publisher, I need to provide a name for the "topic", same for the reader. All documentation about sending or receiving data is speaking about "topics".

When dealing with the HDF5 files, it speaks about "channels" instead of "topics". Even a docu search for "channel" only shows results in the context of HDF5.

This inconsistency should be solved as it causes confusion.
Even the GUIs show different things:
* the ecal monitor shows "Topic"
* the ecal player shows "Channel"

### Proposal

Stick to either of the namings.
I'd suggest to stick to Topics, as this is also known in ROS context.

### Tasks and updates

- [ ] Update the eCAL Player to write "Topic"
- [ ] Update the eCAL MDF5 recordings to use "Topic"
- [ ] Update the docu
