### ISSUE TITLE
`eCAL::hdf5`: enhance API to save information with unique ID.

### ISSUE THREAD

**Issue by KerstinKeller** [eclipse-ecal/ecal#1338]
We want to introduce a new eCAL HDF5 File version v6.

Current file layout:

```
meas.hdf5
 - 0 (binary payload)
 - 1 (binary payload)
 - 2 (binary payload)
 - person (table)
    - attribute topic type
    - attribute topic descriptor
 ```

To facilitate saving TopicDescriptionInformation with different descriptors, we need to change the structure quite a bit
```
 - 0 (binary payload)
 - 1 (binary payload)
 - 2 (binary payload)
 - person
    - PubID
      - TypeInformation
        - name
        - schema
        - descriptor
      - content
```

## Questions
- What datatype should we use? (`std::uint64_t`?)
- How do we make the signature (std::string, std::uint64t) or put them in a struct?

Todo:
- [x] New API that works with `Channel` (name + ID) instead of `std::string` (`channel_name`) (#1375)
- [x] Legacy IP still existing, and implemented in terms of new API.  (#1375)
- [x] Create `ecal_meas_file_v6.h/cpp` for new reader implementation and `ecal_meas_file_writer_v6.h/cpp` for new writer implementation (#1375)
- [ ] Update documentation

**Comment by hannemn** [comment]
Implemented with eCAL 6, documentation is missing.
