### ISSUE TITLE
[docu] Adaption for eCAL 6

### ISSUE THREAD

**Issue by Peguen** [eclipse-ecal/ecal#1672]
### Context

eCAL features, functions and concepts changed while preparing for the eCAL 6 release. During adaption of the configuration management i noticed some sides that are not up-to-date anymore.

### Proposal

Change adapt the description of some functionalities, add more documentation.

### Tasks and updates

- [ ] check for embedded code correctness
- [ ] rework the parts with the former "auto" behaviour
- [ ] build instruction with new dependency handling update @KerstinKeller 
- [ ] What about specific firewall information?
- [ ] Documentation about docker to host communication.
- [ ] Add migration guide for porting user code from eCAL 5 -> eCAL 6
- [ ] Check Python install guide (the whl name changed)

Content to check: 
https://github.com/eclipse-ecal/ecal/blob/master/doc/rst/advanced/layers/shm_zerocopy.rst#combining-zero-copy-and-multibuffering
https://github.com/eclipse-ecal/ecal/blob/master/doc/rst/advanced/layers/udp_mc.rst
https://github.com/eclipse-ecal/ecal/blob/9b5f082f08b8a90fb316cbbde952607f7028521b/doc/rst/advanced/message_drops.rst?plain=1#L35
https://github.com/eclipse-ecal/ecal/blob/master/doc/rst/advanced/transport_layers.rst
